apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - image: prom/node-exporter
        name: node-exporter
        args:
          - --collector.textfile.directory=/var/lib/prometheus/node-exporter/
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --path.rootfs=/rootfs
          - --collector.netclass.ignored-devices=^(lo|docker[0-9]|kube-ipvs0|dummy0|veth.+|br\-.+)$
          - --collector.netdev.ignored-devices=^(lo|docker[0-9]|kube-ipvs0|dummy0|veth.+|br\-.+)$
          - --collector.filesystem.ignored-mount-points=^/(dev|sys|proc|host|etc|var/lib/kubelet|var/lib/docker/.+)($|/)
          - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|efivarfs|tmpfs|nsfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rootfs|rpc_pipefs|securityfs|sysfs|tracefs)$
          - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p|dm-|sr|nbd)\d+$
          - --collector.systemd.unit-whitelist=^((cron|ntp)\.service|user-\d+.slice)$
          - --collector.systemd
          - --no-collector.bcache
          - --no-collector.infiniband
          - --no-collector.wifi
          - --no-collector.ipvs
        resources:
          limits:
            memory: 180Mi
          requests:
            memory: 180Mi
            cpu: 100m
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly:  true
          - name: sys
            mountPath: /host/sys
            readOnly: true
          - mountPath: /rootfs
            name: root-fs
            readOnly: true
          - mountPath: /var/run/dbus/system_bus_socket
            name: dbus
          - mountPath: /var/lib/prometheus/node-exporter/
            name: textfiles
      priorityClassName: high
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root-fs
          hostPath:
            path: /
        - name: dbus
          hostPath:
            path: /var/run/dbus/system_bus_socket
        - name: textfiles
          hostPath:
            path: /var/lib/prometheus/node-exporter/
