groups:
- name: kube-state
  rules:
  - alert: KubeDS
    expr: kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_number_ready >0
    for: 5m
    labels:
      severity: warning
      instance: '{{$labels.daemonset}}'
    annotations:
      description: Daemonset has {{$value}} not ready instance(s)

  - alert: KubeStatefulSet
    expr: kube_statefulset_replicas - kube_statefulset_status_replicas_ready>0
    for: 5m
    labels:
      severity: warning
      instance: '{{$labels.statefulset}}'
    annotations:
      description: StatefulSet has {{$value}} not ready replica(s)

  - alert: KubeDeployment
    expr: kube_deployment_spec_replicas - kube_deployment_status_replicas_available > 0
    for: 5m
    labels:
      severity: warning
      instance: '{{$labels.deployment}}'
    annotations:
      description: Deployment has {{$value}} not ready replica(s)

  - alert: KubeDeploymentStale
    expr: kube_deployment_metadata_generation - kube_deployment_status_observed_generation>0
    for: 5m
    labels:
      severity: informational
      instance: '{{$labels.deployment}}'
    annotations:
      description: Deployment observed is {{$value}} version(s) old

  - alert: KubeRS
    expr: kube_replicaset_owner{owner_is_controller!="true"}
    for: 5m
    labels:
      severity: informational
      instance: '{{ $labels.replicaset }}'
    annotations:
      description: Standalone ReplicaSet found

  - alert: KubeEndpointReady
    expr: kube_endpoint_address_not_ready>0
    for: 5m
    labels:
      severity: informational
      instance: '{{$labels.endpoint}}'
    annotations:
      description: Endpoint address is not ready

  - alert: KubeEndpointAvail
    expr: kube_endpoint_address_available{endpoint!~"kube-controller-manager|kube-scheduler"}==0
    for: 5m
    labels:
      severity: informational
      instance: '{{$labels.endpoint}}'
    annotations:
      description: Endpoint available

  - alert: KubeJob
    expr: kube_job_status_failed>0
    for: 5m
    labels:
      severity: informational
      instance: '{{$labels.exported_job}}{{$labels.job_name}}'
    annotations:
      description: Job failed

  - alert: KubeNodeStatus
    expr: kube_node_status_condition{condition!="Ready", status!="false"} == 1
    for: 1m
    labels:
      severity: informational
      instance: '{{$labels.node}}'
    annotations:
      description: Node {{$labels.condition}} is {{$labels.status}}

  - alert: KubeNodeStatus
    expr: kube_node_status_condition{condition!="Ready", status!="false"} == 1
    for: 5m
    labels:
      severity: warning
      instance: '{{$labels.node}}'
    annotations:
      description: Node {{$labels.condition}} is {{$labels.status}}

  - alert: KubePV
    expr: kube_persistentvolume_status_phase{phase!="Bound"} == 1
    for: 1m
    labels:
      severity: informational
      instance: '{{ $labels.persistentvolume }}'
    annotations:
      description: "PV is {{ $labels.phase }}"

  - alert: KubePVC
    expr: kube_persistentvolumeclaim_status_phase{phase!="Bound"} == 1
    for: 1m
    labels:
      severity: informational
      instance: '{{ $labels.persistentvolumeclaim }}'
    annotations:
      description: "PVC is {{ $labels.phase }}"

  - alert: KubePod
    expr: kube_pod_owner{owner_is_controller!="true", namespace!="kube-system"}
    for: 5m
    labels:
      severity: informational
      instance: '{{ $labels.pod }}'
    annotations:
      description: Standalone Pod found

    #kube_pod_status_ready
    #kube_pod_status_scheduled
    #kube_pod_container_status_waiting
    #kube_pod_status_phase
  - alert: KubePodState
    expr: kube_pod_container_status_waiting_reason > 0
    for: 5m
    labels:
      severity: informational
      instance: '{{ $labels.pod }}'
    annotations:
      description: Pod is {{ $labels.reason }}

  - alert: KubePodRestarting
    expr: increase(kube_pod_container_status_restarts_total[10m]) > 0
    for: 10m
    labels:
      severity: informational
      instance: '{{$labels.pod}}'
    annotations:
      description: '{{printf "%.2f" $value}} restarts last 10m'

  - alert: KubeCronJob
    expr: kube_cronjob_next_schedule_time - time() < -60 and kube_cronjob_next_schedule_time!=-62135596800
    for: 1m
    labels:
      severity: informational
      instance: '{{$labels.cronjob}}'
    annotations:
      description: CronJob stalled

  - alert: KubeCronJobSuspended
    expr: kube_cronjob_spec_suspend > 0
    for: 1m
    labels:
      severity: informational
      instance: '{{$labels.cronjob}}'
    annotations:
      description: CronJob suspended

  - alert: KubeNSTermination
    expr: kube_namespace_status_phase{phase="Terminating"} != 0
    for: 15m
    labels:
      severity: informational
      instance: '{{$labels.namespace}}'
    annotations:
      description: Namespace is terminating

  - alert: KubeNodeCordoned
    expr: kube_node_spec_unschedulable == 1
    for: 15m
    labels:
      severity: informational
      instance: '{{$labels.node}}'
    annotations:
      description: Node is unschedulable
