{
 "title": "Beats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(filebeat_info,monitor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Filebeat Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(filebeat_beat_info_uptime_ms{monitor=\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Filebeat version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(filebeat_info{monitor=\"$monitor\"}) by (version)"
    }
   ]
  },
  {
   "title": "Filebeat Queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(filebeat_libbeat_pipeline{monitor=\"$monitor\", events=\"active\"})"
    }
   ]
  },
  {
   "title": "Journalbeat Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(journalbeat_beat_info_uptime_ms{monitor=\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Journalbeat version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(journalbeat_info{monitor=\"$monitor\"}) by (version)"
    }
   ]
  },
  {
   "title": "Journalbeat Queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(journalbeat_libbeat_pipeline{monitor=\"$monitor\", events=\"active\"})"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Filebeat Output Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(filebeat_libbeat_output{monitor=\"$monitor\", events=~\".+\", events!=\"total\"}[$__interval])) by(events)",
     "legendFormat": "{{events}}"
    },
    {
     "expr": "sum(rate(filebeat_libbeat_output{monitor=\"$monitor\", read=\"errors\"}[$__interval]))",
     "legendFormat": "read_error"
    },
    {
     "expr": "sum(rate(filebeat_libbeat_output{monitor=\"$monitor\", write=\"errors\"}[$__interval]))",
     "legendFormat": "write_error"
    }
   ]
  },
  {
   "title": "Journalbeat Output Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(journalbeat_libbeat_output{monitor=\"$monitor\", events=~\".+\", events!=\"total\"}[$__interval])) by(events)",
     "legendFormat": "{{events}}"
    },
    {
     "expr": "sum(rate(journalbeat_libbeat_output{monitor=\"$monitor\", read=\"errors\"}[$__interval]))",
     "legendFormat": "read_error"
    },
    {
     "expr": "sum(rate(journalbeat_libbeat_output{monitor=\"$monitor\", write=\"errors\"}[$__interval]))",
     "legendFormat": "write_error"
    }
   ]
  },
  {
   "title": "Filebeat Pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(filebeat_libbeat_pipeline{monitor=\"$monitor\", events!~\"active|total\"}[$__interval])) by(events)",
     "legendFormat": "{{events}}"
    }
   ]
  },
  {
   "title": "Journalbeat Pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(journalbeat_libbeat_pipeline{monitor=\"$monitor\", events!=\"total\"}[$__interval])) by(events)",
     "legendFormat": "{{events}}"
    }
   ]
  },
  {
   "title": "Filebeat Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(filebeat_libbeat_output{monitor=\"$monitor\", read=\"bytes\"}[$__interval])) by(kubernetes_pod_node_name)",
     "legendFormat": "read {{kubernetes_pod_node_name}}"
    },
    {
     "expr": "avg(rate(filebeat_libbeat_output{monitor=\"$monitor\", write=\"bytes\"}[$__interval])) by(kubernetes_pod_node_name)",
     "legendFormat": "write {{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "Journalbeat Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(journalbeat_libbeat_output{monitor=\"$monitor\", read=\"bytes\"}[$__interval])) by(kubernetes_pod_node_name)",
     "legendFormat": "read {{kubernetes_pod_node_name}}"
    },
    {
     "expr": "avg(rate(journalbeat_libbeat_output{monitor=\"$monitor\", write=\"bytes\"}[$__interval])) by(kubernetes_pod_node_name)",
     "legendFormat": "write {{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "Filebeat Working Set ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{monitor=~\"$monitor\", container_name=\"filebeat\"}) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{monitor=~\"$monitor\", container_name=\"filebeat\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Journalbeat Working Set ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{monitor=~\"$monitor\", container_name=\"journalbeat\"}) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{monitor=~\"$monitor\", container_name=\"journalbeat\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}