{
 "title": "Capacity: Overview",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(nginx_activity_total{environment=\"Prod\"}, monitor)"
   },
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{monitor=\"$monitor\"}, instance)"
   },
   {
    "name": "stack",
    "query": "label_values(nginx_activity_total{monitor=\"$monitor\"}, stack)"
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_activity_total{monitor=\"$monitor\"}[$__interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "5xx by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_activity_total{monitor=\"$monitor\", status=~\"5..\", error_code!~\"ClientUpgradeRequired|FileMissing|InternalAuthService|InternalDeadlock|InternalHostPilot\"}[$__interval])) by (service, error_code)",
     "legendFormat": "{{service}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"users_with_content\"}",
     "legendFormat": "users with content"
    },
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"users\", last_active=\"30\"}",
     "legendFormat": "users active last month"
    },
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"users\", last_active=\"7\"}",
     "legendFormat": "users active last week"
    },
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"users\", last_active=\"1\"}",
     "legendFormat": "users active last day"
    }
   ]
  },
  {
   "title": "Provisioned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Users" }
   ],
   "targets": [
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"users\", is_test=\"\", last_active=\"\"}",
     "legendFormat": "users"
    },
    {
     "expr": "srs_customers_total{stack=\"$stack\", type=\"organizations\", is_test=\"\"}",
     "legendFormat": "organizations"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sum Host CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{monitor=~\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{monitor=~\"$monitor\", instance=~\"$instance\", container_name!=\"\"})/1024"
    }
   ]
  },
  {
   "title": "Sum Host RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{monitor=~\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Mem Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} or kube_pod_container_resource_requests_memory_bytes{monitor=~\"$monitor\", node=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Mem Limits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{monitor=~\"$monitor\", instance=~\"$instance\", container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Sum Host FS ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint!~\"/|/var/lib/docker|/boot\"})"
    }
   ]
  },
  {
   "title": "Used FS ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint!~\"/|/var/lib/docker|/boot\"}) -sum(node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint!~\"/|/var/lib/docker|/boot\"})"
    }
   ]
  },
  {
   "title": "LA15 / Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{monitor=\"$monitor\"}) by(instance) / count(node_cpu_seconds_total{monitor=\"$monitor\", mode=\"idle\"}) by(instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Warn" }
   ]
  },
  {
   "title": "Memory usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes{monitor=\"$monitor\"} + node_memory_Buffers_bytes{monitor=\"$monitor\"} + node_memory_Inactive_file_bytes{monitor=\"$monitor\"} + node_memory_SReclaimable_bytes{monitor=\"$monitor\"})/node_memory_MemTotal_bytes{monitor=\"$monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Sum by Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(8*rate(node_network_transmit_bytes_total{monitor=~\"$monitor\", device=~\"(vlan|bond|eth|ens).*\"}[$__interval])) by(device)",
     "legendFormat": "{{device}} out"
    },
    {
     "expr": "sum(8*rate(node_network_receive_bytes_total{monitor=~\"$monitor\", device=~\"(vlan|bond|eth|ens).*\"}[$__interval])) by(device)",
     "legendFormat": "{{device}} in"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{monitor=\"$monitor\", mountpoint!~\"/|/var|/boot|/var/lib/(docker|etcd)\"} - node_filesystem_avail_bytes{monitor=\"$monitor\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{monitor=\"$monitor\", mountpoint!~\"/|/var|/boot|/var/lib/(docker|etcd)\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "1 - (node_filesystem_avail_bytes{monitor=\"$monitor\", mountpoint!~\"/|/var|/boot|/var/lib/(docker|etcd)\"} / node_filesystem_size_bytes{monitor=\"$monitor\"})",
     "legendFormat": "Used, %"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "NFS stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total{monitor=\"$monitor\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Bucket size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(objstore_used_bytes{stack=\"$stack\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "LA15 / Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{stack=\"$stack\", instance=~\".*fmdb-[^re].*\"}) by(instance) / count(node_cpu_seconds_total{stack=\"$stack\", instance=~\".*fmdb-.*\", mode=\"idle\"}) by(instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Warn" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{stack=\"$stack\", instance=~\".*fmdb-[^re].*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Inactive_file_bytes - node_memory_SReclaimable_bytes",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{stack=\"$stack\", instance=~\".*fmdb-[^re].*\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{stack=\"$stack\", instance!~\".*restore.*\", mountpoint=~\".*lib/mysql\"}-node_filesystem_avail_bytes",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    },
    {
     "expr": "min(node_filesystem_size_bytes{stack=\"$stack\", instance!~\".*restore.*\", mountpoint=~\".*lib/mysql\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queries/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(mysql_global_status_questions{stack=\"$stack\"}[$__interval])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "100% = 1 vCPU core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{monitor=\"$monitor\", container_name=\"rabbitmq\"}[$__interval])) by(pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{monitor=\"$monitor\", container_name=\"rabbitmq\"}) by(pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{monitor=\"$monitor\", container_name=\"rabbitmq\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Exchange rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(rabbitmq_exchange_messages_published_in_total{monitor=\"$monitor\"}[$__interval])) by(vhost,exchange,type)",
     "legendFormat": "{{vhost}}/{{exchange}}/{{type}} in"
    },
    {
     "expr": "max(rate(rabbitmq_exchange_messages_published_out_total{monitor=\"$monitor\"}[$__interval])) by(vhost,exchange,type)",
     "legendFormat": "{{vhost}}/{{exchange}}/{{type}} out"
    }
   ]
  },
  {
   "title": "Messages queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_messages{monitor=\"$monitor\", queue!~\"message.*\"}) by(vhost,queue)",
     "legendFormat": "{{vhost}}/{{queue}}"
    }
   ]
  },
  { "title": "ElasticSearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Cluster Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{stack=\"$stack\"})",
     "legendFormat": "Running Nodes"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{stack=\"$stack\"})",
     "legendFormat": "Active Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_unassigned_shards{stack=\"$stack\"})",
     "legendFormat": "Unassigned Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_initializing_shards{stack=\"$stack\"})",
     "legendFormat": "Init-ing Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{stack=\"$stack\"})",
     "legendFormat": "Relocating Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_delayed_unassigned_shards{stack=\"$stack\"})",
     "legendFormat": "Delayed Unassigned Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{stack=\"$stack\"})",
     "legendFormat": "Primary Shards"
    }
   ]
  },
  {
   "title": "Documents (xReplica)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{stack=\"$stack\",})",
     "legendFormat": "Indexed"
    },
    {
     "expr": "sum(elasticsearch_indices_docs_deleted{stack=\"$stack\",})",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_jvm_memory_used_bytes{stack=\"$stack\", area=\"heap\"}) by(name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "min(elasticsearch_jvm_memory_committed_bytes{stack=\"$stack\", area=\"heap\", es_data_node=\"true\"})",
     "legendFormat": "{{ name }} heap size"
    }
   ]
  },
  {
   "title": "Index data size per node",
   "type": "graph",
   "description": "Current size of stored index data in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_indices_store_size_bytes{stack=\"$stack\"}) by(name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}