{
 "title": "Ceph: overview",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [ "mon" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(ceph_health_status, monitor)"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_health_status{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{monitor=~\"$monitor\"}-ceph_cluster_total_used_bytes{monitor=~\"$monitor\"})/ceph_cluster_total_bytes{monitor=~\"$monitor\"}"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{monitor=~\"$monitor\"}==1)"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_stored{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_cluster_total_used_bytes{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)/2"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_cluster_total_bytes{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)/2"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_in{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up{monitor=~\"$monitor\"}) - count(ceph_osd_in{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_up{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up{monitor=~\"$monitor\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{monitor=~\"$monitor\"})"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_cluster_total_bytes{monitor=~\"$monitor\"})",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "avg(ceph_cluster_total_used_bytes{monitor=~\"$monitor\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum(rate(ceph_osd_op_w_in_bytes{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "8*sum(rate(ceph_osd_op_r_out_bytes{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{monitor=~\"$monitor\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{monitor=~\"$monitor\"})",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "OSD Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_process_latency_count{monitor=~\"$monitor\"}[$__interval])",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "MDS Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_server_req_lookupparent_latency_count{monitor=~\"$monitor\"}",
     "legendFormat": "lookupparent"
    },
    {
     "expr": "ceph_mds_subtrees{monitor=~\"$monitor\"}",
     "legendFormat": "lookupparent"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_pg_active{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Active"
    },
    {
     "expr": "avg(ceph_pg_clean{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Clean"
    },
    {
     "expr": "avg(ceph_pg_peering{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Peering"
    },
    {
     "expr": "avg(ceph_pg_degraded{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Degraded"
    },
    {
     "expr": "avg(ceph_pg_stale{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Stale"
    },
    {
     "expr": "avg(ceph_unclean_pgs{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Unclean"
    },
    {
     "expr": "avg(ceph_pg_undersized{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Undersized"
    },
    {
     "expr": "avg(ceph_pg_incomplete{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "avg(ceph_pg_forced_backfill{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "avg(ceph_pg_inconsistent{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "avg(ceph_pg_forced_recovery{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "avg(ceph_pg_creating{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Creating"
    },
    {
     "expr": "avg(ceph_pg_wait_backfill{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "avg(ceph_pg_deep{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Deep"
    },
    {
     "expr": "avg(ceph_pg_scrubbing{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "avg(ceph_pg_recovering{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Recovering"
    },
    {
     "expr": "avg(ceph_pg_repair{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Repair"
    },
    {
     "expr": "avg(ceph_pg_down{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Down"
    },
    {
     "expr": "avg(ceph_pg_peered{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Peered"
    },
    {
     "expr": "avg(ceph_pg_backfill{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Backfill"
    },
    {
     "expr": "avg(ceph_pg_remapped{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Remapped"
    },
    {
     "expr": "avg(ceph_pg_backfill_toofull{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Objects in the Cluster (ceph13 only)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_cluster_total_objects{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Objects in thee Cluster (Ceph v14)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(ceph_pool_objects{monitor=~\"$monitor\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "RECOVERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_pg_degraded{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Degraded"
    },
    {
     "expr": "avg(ceph_pg_stale{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Stale"
    },
    {
     "expr": "avg(ceph_pg_undersized{monitor=~\"$monitor\"}) without(instance, kubernetes_pod_node_name)",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{monitor=~\"$monitor\"}[15s]))",
     "legendFormat": "OPS"
    }
   ]
  }
 ]
}