{
 "title": "Container: compare details",
 "tags": [
  "mon",
  "cadvisor"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(cadvisor_version_info,monitor)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_working_set_bytes{monitor=~\"$monitor\"}, container_name)"
   },
   {
    "name": "pod",
    "query": "label_values(container_memory_working_set_bytes{monitor=~\"$monitor\", container_name=~\"$container\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU usage, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_cpu_system_seconds_total{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "max(rate(container_cpu_user_seconds_total{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_cache{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "cache"
    },
    {
     "expr": "max(container_memory_working_set_bytes{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "working_set"
    },
    {
     "expr": "max(container_memory_rss{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "rss"
    },
    {
     "expr": "max(container_memory_mapped_file{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "mapped_file"
    },
    {
     "expr": "max(container_memory_swap{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "swap"
    },
    {
     "expr": "max(container_memory_usage_bytes{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{monitor=~\"$monitor\", container_name=~\"$container\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU throttled, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{monitor=~\"$monitor\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*rate(container_network_receive_bytes_total{monitor=~\"$monitor\", pod_name=~\"$pod\", image!=\"\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "8*rate(container_network_transmit_bytes_total{monitor=~\"$monitor\", pod_name=~\"$pod\", image!=\"\"}[5m])",
     "legendFormat": "out"
    }
   ]
  }
 ]
}