{
 "title": "Container: overview",
 "description": "cadvisor stats",
 "tags": [
  "mon",
  "cadvisor"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(cadvisor_version_info,monitor)"
   },
   {
    "name": "instance",
    "query": "label_values(cadvisor_version_info{monitor=~\"$monitor\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_last_seen{monitor=~\"$monitor\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sum Host CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{monitor=~\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{monitor=~\"$monitor\", instance=~\"$instance\", container!=\"\"})/1024"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{monitor=~\"$monitor\", instance=~\"$instance\", container!=\"\"})/100000"
    }
   ]
  },
  {
   "title": "Sum Host RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{monitor=~\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Mem Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} or kube_pod_container_resource_requests_memory_bytes{monitor=~\"$monitor\", node=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Mem Limits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{monitor=~\"$monitor\", instance=~\"$instance\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Cumulative CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Cumulative WorkingSet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Min Cumulative Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - min by(container) (container_start_time_seconds{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Max Cumulative Memory % limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (container) (container_memory_working_set_bytes{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"}/container_spec_memory_limit_bytes{monitor=~\"$monitor\", instance=~\"$instance\", image!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Sum Disk IO/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_total{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"}[$__interval]))",
     "legendFormat": "{{container}} reads"
    },
    {
     "expr": "sum by(container) (rate(container_fs_writes_total{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"}[$__interval]))",
     "legendFormat": "{{container}} writes"
    }
   ]
  },
  {
   "title": "Sum Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum by(container) (rate(container_network_receive_bytes_total{monitor=~\"$monitor\", instance=~\"$instance\", image!=\"\", namespace=~\"$namespace\", container!=\"node-exporter\"}[$__interval]))",
     "legendFormat": "{{container}} in"
    },
    {
     "expr": "8*sum by(container) (rate(container_network_transmit_bytes_total{monitor=~\"$monitor\", instance=~\"$instance\", image!=\"\", namespace=~\"$namespace\", container!=\"node-exporter\"}[$__interval]))",
     "legendFormat": "{{container}} out"
    }
   ]
  },
  {
   "title": "Sum Used Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_fs_usage_bytes{monitor=~\"$monitor\", instance=~\"$instance\", namespace=~\"$namespace\", image!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}