{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(coredns_dns_request_count_total, monitor)"
   },
   {
    "name": "instance",
    "query": "label_values(coredns_dns_request_count_total{monitor=\"$monitor\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Coredns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - min(process_start_time_seconds{monitor=\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coredns_build_info{monitor=\"$monitor\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_info{monitor=\"$monitor\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(coredns_panic_count_total{monitor=\"$monitor\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RSS Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{monitor=\"$monitor\"}[$__interval])) by (type, zone)",
     "legendFormat": "{{type}}/{{zone}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{monitor=\"$monitor\"}[5m])) by (zone, proto)",
     "legendFormat": "{{proto}}/{{zone}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_request_duration_seconds_bucket{monitor=\"$monitor\", zone!=\"dropped\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests Size, UDP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_request_size_bytes_bucket{monitor=\"$monitor\", proto=\"udp\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests Size, TCP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_request_size_bytes_bucket{monitor=\"$monitor\", proto=\"tcp\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{monitor=\"$monitor\"}[$__interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Response Size, UDP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_response_size_bytes_bucket{monitor=\"$monitor\", proto=\"udp\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Size, TCP",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_response_size_bytes_bucket{monitor=\"$monitor\", proto=\"tcp\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache (size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_size{monitor=\"$monitor\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{monitor=\"$monitor\"}[$__interval])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{monitor=\"$monitor\"}[$__interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  { "title": "Forward", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Forward fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_healthcheck_failure_count_total{monitor=\"$monitor\"}[$__interval])) by(to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Forward request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "avg(rate(coredns_forward_request_duration_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Forwards/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_request_count_total{monitor=\"$monitor\"}[$__interval])) by(to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Health request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "avg(rate(coredns_health_request_duration_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Forward response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_response_rcode_count_total{monitor=\"$monitor\"}[$__interval])) by(rcode, to)",
     "legendFormat": "{{to}}/{{rcode}}"
    }
   ]
  }
 ]
}