{
 "title": "Elasticsearch: details",
 "description": "Dashboard to view metrics of elasticsearch_exporter on each elasticsearch servers",
 "tags": [ "mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(elasticsearch_process_cpu_percent{cluster=\"$cluster\"},name)"
   },
   {
    "name": "monitor",
    "label": "node",
    "query": "label_values(elasticsearch_process_cpu_percent{cluster=\"$cluster\"},monitor)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"green\"}) * 3\n+\navg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"yellow\"}) * 2\n+\navg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"red\"}) * 1"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{cluster=\"$cluster\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\", name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Init-ing Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Cluster Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Cluster Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})",
     "legendFormat": "Running Nodes"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})",
     "legendFormat": "Active Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"})",
     "legendFormat": "Unassigned Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"})",
     "legendFormat": "Init-ing Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"})",
     "legendFormat": "Relocating Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"})",
     "legendFormat": "Delayed Unassigned Shards"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"})",
     "legendFormat": "Primary Shards"
    }
   ]
  },
  {
   "title": "Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_timed_out{cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{ instance }} time out"
    },
    {
     "expr": "elasticsearch_cluster_health_status{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}/{{color}}"
    }
   ]
  },
  { "title": "Machine Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(elasticsearch_process_cpu_percent{cluster=~\"$cluster\", name=~\"$node\"}[5m])",
     "legendFormat": "{{ name }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "description": "JVM memory currently used by area",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster\", name=~\"$node\", area=\"heap\"}) by(name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "min(elasticsearch_jvm_memory_committed_bytes{cluster=~\"$cluster\", name=~\"$node\", area=\"heap\", es_data_node=\"true\"})",
     "legendFormat": "{{ name }} heap size"
    },
    {
     "expr": "avg(elasticsearch_jvm_memory_committed_bytes{cluster=~\"$cluster\", name=~\"$node\", area=\"non-heap\"}) by(name)",
     "legendFormat": "{{ name }} non-heap"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_filesystem_io_stats_device_read_operations_count{cluster=~\"$cluster\", name=~\"$node\"}[1m])",
     "legendFormat": "{{ name }} reads"
    },
    {
     "expr": "rate(elasticsearch_filesystem_io_stats_device_write_operations_count{cluster=~\"$cluster\", name=~\"$node\"}[1m])",
     "legendFormat": "{{ name }} writes"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "description": "Used size of block device in percent",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", name=~\"$node\", es_data_node=\"true\"}/elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Document Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Documents x Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=~\"$cluster\", name=~\"$node\"})",
     "legendFormat": "Indexed"
    },
    {
     "expr": "sum(elasticsearch_indices_docs_deleted{cluster=~\"$cluster\", name=~\"$node\"})",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Index data size per node",
   "type": "graph",
   "description": "Current size of stored index data in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC rate (young)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC rate (old)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC seconds (young)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])) by (name) / sum(rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[5m])) by (name) / sum(irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[5m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC seconds (old)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])) by (name) / sum(rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[5m])) by (name) / sum(irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[5m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))",
       "legendFormat": "query"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))",
       "legendFormat": "fetch"
      }
     ]
    },
    {
     "title": "Get Latencies",
     "type": "graph",
     "description": "Average get time in seconds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_get_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) \nor\nsum(irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)  / sum(irate(elasticsearch_indices_get_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) ",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Indexing Latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
       "legendFormat": "index"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "Merges",
     "type": "graph",
     "description": "Average merge size in bytes and time spent merging in seconds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_merges_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_merges_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
       "legendFormat": "{{ name }} time"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_merges_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_merges_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
       "legendFormat": "{{ name }} size"
      }
     ]
    },
    {
     "title": "Flush",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_flush_total\t{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_flush_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Refresh",
     "type": "graph",
     "description": "Average time spent refreshing in seconds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_refresh_total\t{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_refresh_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Thread Pools in 1min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_thread_pool_completed_count{cluster=~\"$cluster\", type!=\"management\", name=~\"$node\"}[$__interval])) by (type) or sum(irate(elasticsearch_thread_pool_completed_count{cluster=~\"$cluster\", type!=\"management\", name=~\"$node\"}[5m])) by (type)",
       "legendFormat": " {{ type }}"
      }
     ]
    },
    {
     "title": "Queue Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\", name=~\"$node\"}) by (type)",
       "legendFormat": "Type: {{type}}"
      }
     ]
    },
    {
     "title": "Active Thread",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", name=~\"$node\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Queue completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_thread_pool_completed_count{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Thread pool rejections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\", name=~\"$node\"}[$__interval])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transport Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets",
     "type": "graph",
     "description": "Count of packets received and sent",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_transport_rx_packets_total{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])",
       "legendFormat": "{{ name }} RX"
      },
      {
       "expr": "rate(elasticsearch_transport_tx_packets_total{cluster=~\"$cluster\", name=~\"$node\"}[$__interval]) * -1",
       "legendFormat": "{{ name }} TX"
      }
     ]
    },
    {
     "title": "Transport",
     "type": "graph",
     "description": "Total number of bytes received and total number of bytes sent.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_transport_rx_size_bytes_total{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])",
       "legendFormat": "{{ name }} RX"
      },
      {
       "expr": "rate(elasticsearch_transport_tx_size_bytes_total{cluster=~\"$cluster\", name=~\"$node\"}[$__interval]) * -1 ",
       "legendFormat": "{{ name }} TX"
      }
     ]
    }
   ]
  },
  {
   "title": "Fielddata Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fielddata evictions",
     "type": "graph",
     "description": "Evictions from field data",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_fielddata_evictions{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name)",
       "legendFormat": "{{ name }} evictions"
      }
     ]
    },
    {
     "title": "Fielddata size",
     "type": "graph",
     "description": "Field data cache memory usage in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_fielddata_memory_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query cache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query cache hit/miss",
     "type": "graph",
     "description": "Count of query cache hit/miss",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_query_cache_count{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, cache)",
       "legendFormat": "{{ name }} {{ cache }}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "description": "Evictions from query cache",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])\nor\nirate(elasticsearch_indices_query_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[5m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "description": "Size of query cache",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_cache_size{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Query cache usage",
     "type": "graph",
     "description": "Query cache memory usage in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request cache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request cache hit/miss",
     "type": "graph",
     "description": "Count of request cache hit/miss",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_request_cache_count{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, cache)",
       "legendFormat": "{{ name }} {{ cache }}"
      }
     ]
    },
    {
     "title": "Request cache evictions",
     "type": "graph",
     "description": "Evictions from request cache",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_indices_request_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index data Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index throttle time",
     "type": "graph",
     "description": "Throttle time for index store in seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=~\"$cluster\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Segments Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations",
     "type": "graph",
     "description": "Total translog operations",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_translog_operations{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Translog size",
     "type": "graph",
     "description": "Total translog size in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_translog_size_in_bytes{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breaker Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Breaker",
     "type": "graph",
     "description": "Estimated size in percent of breaker",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_breakers_estimated_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (breaker) / sum(elasticsearch_breakers_limit_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (breaker)",
       "legendFormat": "{{ breaker }}"
      }
     ]
    },
    {
     "title": "Breaker tripped",
     "type": "graph",
     "description": "tripped for breaker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_breakers_tripped{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, breaker)",
       "legendFormat": "{{ name }} {{ breaker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual memory",
     "type": "graph",
     "description": "Total virtual memory used in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_mem_virtual_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "graph",
     "description": "Open file descriptors",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_open_files_count{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  }
 ]
}