{
 "title": "etcd",
 "tags": [ "mon" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(etcd_server_version,monitor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Etcd has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(etcd_server_has_leader{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(etcd_server_version{monitor=~\"$monitor\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "max(etcd_server_version{monitor=~\"$monitor\"})by(server_version)",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{monitor=~\"$monitor\", grpc_type=\"unary\", grpc_code=\"OK\"}[$__interval]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{monitor=~\"$monitor\", grpc_type=\"unary\", grpc_code!=\"OK\"}[$__interval]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{monitor=~\"$monitor\", grpc_service=\"etcdserverpb.Watch\"}) - sum(grpc_server_handled_total{monitor=~\"$monitor\", grpc_service=\"etcdserverpb.Watch\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{monitor=~\"$monitor\", grpc_service=\"etcdserverpb.Lease\"}) - sum(grpc_server_handled_total{monitor=~\"$monitor\", grpc_service=\"etcdserverpb.Lease\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{monitor=~\"$monitor\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{monitor=~\"$monitor\", job=\"etcd\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Disk Commit Duration perc99",
   "type": "graph",
   "description": "https://coreos.com/etcd/docs/3.2.17/faq.html\nUsually this issue is caused by a slow disk. The disk could be experiencing contention among etcd and other applications, or the disk is too simply slow (e.g., a shared virtualized disk). To rule out a slow disk from causing this warning, monitor backend_commit_duration_seconds (p99 duration should be less than 25ms) to confirm the disk is reasonably fast. If the disk is too slow, assigning a dedicated disk to etcd or using faster disk will typically solve the problem.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{monitor=~\"$monitor\"}[1h])",
     "legendFormat": "{{instance}} Total Leader Elections Per Hour"
    }
   ]
  },
  {
   "title": "Disk WAL Duration perc99",
   "type": "graph",
   "description": "https://coreos.com/etcd/docs/3.2.17/faq.html\nUsually this issue is caused by a slow disk. Before the leader sends heartbeats attached with metadata, it may need to persist the metadata to disk. The disk could be experiencing contention among etcd and other applications, or the disk is too simply slow (e.g., a shared virtualized disk). To rule out a slow disk from causing this warning, monitor wal_fsync_duration_seconds (p99 duration should be less than 10ms) to confirm the disk is reasonably fast. If the disk is too slow, assigning a dedicated disk to etcd or using faster disk will typically solve the problem.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "{{instance}} WAL "
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{monitor=~\"$monitor\"})",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Disks latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "The latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{monitor=~\"$monitor\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*rate(etcd_network_client_grpc_received_bytes_total{monitor=~\"$monitor\"}[$__interval])",
     "legendFormat": "{{instance}} In"
    },
    {
     "expr": "8*rate(etcd_network_client_grpc_sent_bytes_total{monitor=~\"$monitor\"}[$__interval])",
     "legendFormat": "{{instance}} Out"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum(rate(etcd_network_peer_received_bytes_total{monitor=~\"$monitor\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}} In"
    },
    {
     "expr": "8*sum(rate(etcd_network_peer_sent_bytes_total{monitor=~\"$monitor\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}} Out"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*sum(rate(etcd_network_client_grpc_received_bytes_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "8*sum(rate(etcd_network_client_grpc_sent_bytes_total{monitor=~\"$monitor\"}[$__interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Peer round-trip time (perc95)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, etcd_network_peer_round_trip_time_seconds_bucket{monitor=~\"$monitor\"})",
     "legendFormat": "{{instance}}->{{To}}"
    }
   ]
  }
 ]
}