{
 "title": "Host: overview",
 "tags": [
  "mon",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "monitor",
    "query": "label_values(node_exporter_build_info{instance=~\"$instance\"}, monitor)"
   },
   {
    "name": "mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}, mountpoint)"
   },
   {
    "name": "nginx",
    "query": "label_values(nginx_connections_handled{monitor=~\"$monitor\", instance=~\"$instance\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime: $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{monitor=~\"$monitor\", instance=~\"$instance\"} - node_boot_time_seconds{monitor=~\"$monitor\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\", mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "repeat": "instance",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_exporter_build_info{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\", mode!=\"idle\"}[$__interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "LA/Core: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{monitor=~\"$monitor\", instance=~\"$instance\"})/count(node_cpu_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "15m"
    },
    {
     "expr": "avg(node_load5{monitor=~\"$monitor\", instance=~\"$instance\"})/ count(node_cpu_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load1{monitor=~\"$monitor\", instance=~\"$instance\"})/ count(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Memory: $instance",
   "type": "graph",
   "description": "PageCache: ActiveFile + InactiveFile\nBuffers: Relatively temporary storage for raw disk blocks (ex. ext4 journal)\nCached: PageCache - Buffers\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_Active_file_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_Shmem_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_Inactive_file_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_SReclaimable_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_MemFree_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Active_file_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} + node_memory_Shmem_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} ",
     "legendFormat": "ActiveFile"
    },
    {
     "expr": "node_memory_Inactive_file_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} + node_memory_SReclaimable_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "InactiveFile"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} ",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk utilization: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem used: $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} / node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "{{mountpoint}} = {{device}}"
    }
   ]
  },
  {
   "title": "IO/s: $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{device}} read/s"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{device}} write/s"
    }
   ]
  },
  {
   "title": "Network usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*rate(node_network_transmit_bytes_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{device}} out"
    },
    {
     "expr": "8*rate(node_network_receive_bytes_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{device}} in"
    }
   ]
  },
  {
   "title": "Logged users: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{monitor=~\"$monitor\", instance=~\"$instance\", name=~\"user-.*.slice\", state=\"active\"}==1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Nginx: $nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "nginx" },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_connections_active{monitor=~\"$monitor\", instance=~\"$nginx\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(nginx_connections_reading{monitor=~\"$monitor\", instance=~\"$nginx\"})",
     "legendFormat": "reading"
    },
    {
     "expr": "sum(nginx_connections_waiting{monitor=~\"$monitor\", instance=~\"$nginx\"})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(nginx_connections_writing{monitor=~\"$monitor\", instance=~\"$nginx\"})",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{monitor=~\"$monitor\", instance=~\"$nginx\"}[$__interval]))",
     "legendFormat": "requests/s"
    },
    {
     "expr": "sum(irate(nginx_connections_accepted{monitor=~\"$monitor\", instance=~\"$nginx\"}[$__interval]))",
     "legendFormat": "accepted/s"
    },
    {
     "expr": "sum(irate(nginx_connections_handled{monitor=~\"$monitor\", instance=~\"$nginx\"}[$__interval]))",
     "legendFormat": "handled/s"
    }
   ]
  },
  {
   "title": "Filesystem Usage: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 90 },
     "repeat": "mountpoint",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Size {{device}} {{fstype}} "
      },
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used on {{mountpoint}}"
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 90 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Size {{device}} {{fstype}} "
      },
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used on {{mountpoint}}"
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Size {{device}} {{fstype}} "
      },
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used on {{mountpoint}}"
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 90 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Size {{device}} {{fstype}} "
      },
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used on {{mountpoint}}"
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Size {{device}} {{fstype}} "
      },
      {
       "expr": "node_filesystem_size_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=~\"$monitor\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "legendFormat": "Used on {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg_over_time(node_procs_running{monitor=~\"$monitor\", instance=~\"$instance\"}[5m]) - 1",
       "legendFormat": "Runnable Processes"
      },
      {
       "expr": "avg_over_time(node_procs_blocked{monitor=~\"$monitor\", instance=~\"$instance\"}[5m])",
       "legendFormat": "Blocked Processes"
      },
      {
       "expr": "irate(node_forks_total{monitor=~\"$monitor\", instance=~\"$instance\"}[5m])",
       "legendFormat": "Created Processes (Forks)"
      }
     ]
    },
    {
     "title": "Interrupts and Context Switches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_context_switches_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "irate(node_intr_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapFree_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{monitor=~\"$monitor\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "irate(node_vmstat_pswpin{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "irate(node_vmstat_pswpout{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_netstat_Tcp_RetransSegs{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Segments Retransmitted"
      },
      {
       "expr": "scalar(rate(node_netstat_Tcp_RetransSegs{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval]))/sum(rate(node_network_transmit_packets_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Retransmit Ratio"
      }
     ]
    },
    {
     "title": "Local Network Errors",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(irate(node_network_receive_errs_total{instance=~\"$host\", device!=\"lo\"}[5m]))",
       "legendFormat": "Receive Errors"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{monitor=~\"$monitor\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Transmit Errors"
      },
      {
       "expr": "sum(irate(node_network_receive_drop_total{monitor=~\"$monitor\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Receive Drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{monitor=~\"$monitor\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Transmit Drop"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{monitor=~\"$monitor\", instance=~\"$instance\"}[5m])",
       "legendFormat": "ListenOverflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{monitor=~\"$monitor\", instance=~\"$instance\"}[5m])",
       "legendFormat": "ListenDrops"
      }
     ]
    },
    {
     "title": "Disk IO Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(node_disk_read_time_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])) / sum(irate(node_disk_reads_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "(sum(irate(node_disk_write_time_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])) / sum(irate(node_disk_writes_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[$__interval])))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "(sum(rate(node_disk_read_time_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\"}[1h])) / sum(rate(node_disk_reads_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[1h])))",
       "legendFormat": "Avg Read Latency (1h)"
      },
      {
       "expr": "(sum(rate(node_disk_write_time_seconds_total{monitor=~\"$monitor\", instance=~\"$instance\"}[1h])) / sum(rate(node_disk_writes_completed_total{monitor=~\"$monitor\", instance=~\"$instance\"}[1h])))",
       "legendFormat": "Avg Write Latency (1h)"
      }
     ]
    },
    {
     "title": "Conntrack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{monitor=~\"$monitor\", instance=~\"$instance\"}",
       "legendFormat": "entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{monitor=~\"$monitor\", instance=~\"$instance\"}",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}