{
 "title": "Host: SMART",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, instance)"
   },
   {
    "name": "monitor",
    "query": "label_values(smartmon_smartctl_version{instance=\"$instance\"}, monitor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disks with SMART",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(smartmon_device_smart_available{monitor=\"$monitor\", instance=\"$instance\"}==1)"
    }
   ]
  },
  {
   "title": "Wearout",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartmon_media_wearout_indicator_value{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "smartctl ver.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartmon_smartctl_version{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SMART info",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "(smartmon_device_smart_available{monitor=\"$monitor\", instance=\"$instance\"}==1) + on(instance,disk, type) group_right() smartmon_device_info{monitor=\"$monitor\", instance=\"$instance\"}"
    },
    {
     "expr": "avg(smartmon_device_smart_healthy{monitor=\"$monitor\", instance=\"$instance\"} and smartmon_device_smart_available{monitor=\"$monitor\", instance=\"$instance\"}==1) by(disk,type)"
    },
    {
     "expr": "avg(smartmon_grown_defects_count_raw_value{monitor=\"$monitor\", instance=\"$instance\"}) by(disk,type)"
    },
    {
     "expr": "avg(smartmon_reallocated_sector_ct_raw_value{monitor=\"$monitor\", instance=\"$instance\"}) by(disk,type)"
    },
    {
     "expr": "avg(smartmon_power_cycle_count_raw_value{monitor=\"$monitor\", instance=\"$instance\"}) by(disk,type)"
    },
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{monitor=\"$monitor\", instance=\"$instance\"}) by(disk,type)"
    },
    {
     "expr": "avg(smartmon_power_on_hours_raw_value{monitor=\"$monitor\", instance=\"$instance\"}) by(disk,type)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "{{type}} {{disk}}"
    }
   ]
  },
  {
   "title": "Read errors/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(smartmon_raw_read_error_rate_raw_value{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{type}} {{disk}}"
    }
   ]
  },
  {
   "title": "SMART disabled",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "(smartmon_device_smart_available{monitor=\"$monitor\", instance=\"$instance\"}==0) + on(instance,disk, type) group_right() smartmon_device_info"
    }
   ]
  }
 ]
}