{
 "title": "JVM: overview",
 "tags": [ "mon" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(cadvisor_version_info,monitor)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{monitor=\"$monitor\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{instance}} heap commited"
    },
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{instance}} heap used"
    },
    {
     "expr": "jvm_memory_bytes_init{instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{instance}} heap size"
    },
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\", area=\"nonheap\"}",
     "legendFormat": "{{instance}} nonheap used"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} RSS"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool=~\".*Old Gen\"}",
     "legendFormat": "{{instance}}/{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_init{instance=~\"$instance\", pool=~\".*Old Gen\"}",
     "legendFormat": "{{instance}}/limit"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} uptime"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}/{{gc}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}/{{gc}}"
    }
   ]
  },
  {
   "title": "Memory pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", pool!~\".*(Old Gen|Eden Space)\"}",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jmx_scrape_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/current"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}/deadlocked_monitor"
    }
   ]
  }
 ]
}