{
 "title": "Minio",
 "tags": [ "mon" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(minio_network_sent_bytes_total, monitor)"
   }
  ]
 },
 "panels": [
  {
   "title": "GET time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_bucket{monitor=~\"$monitor\", request_type=\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "PUT time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_bucket{monitor=~\"$monitor\", request_type=\"PUT\"}[1m])"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*rate(minio_network_received_bytes_total{monitor=~\"$monitor\"}[1m])",
     "legendFormat": "{{instance}} in"
    },
    {
     "expr": "8*rate(minio_network_sent_bytes_total{monitor=~\"$monitor\"}[1m])",
     "legendFormat": "{{instance}} out"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"minio\", monitor=~\"$monitor\"}[1m])"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{app=\"minio\", monitor=~\"$monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"minio\", monitor=~\"$monitor\"}",
     "legendFormat": "{{instance}} RSS"
    }
   ]
  }
 ]
}