{
 "title": "Mysql: overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(mysqld_exporter_build_info, monitor)"
   },
   {
    "name": "instance",
    "query": "label_values(mysqld_exporter_build_info{monitor=~\"$monitor\"}, instance)"
   },
   {
    "name": "stack",
    "query": "label_values(mysqld_exporter_build_info{monitor=\"$monitor\", instance=\"$instance\"}, stack)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ver",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "mysql_version_info{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "{{innodb_version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_status_uptime{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Buffer Pool",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_instances{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Read-Only",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Super RO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_super_read_only{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "PXC nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "PXC cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "PXC cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_connected{monitor=\"$monitor\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Connection errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_aborted_clients{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "aborted clients"
    },
    {
     "expr": "rate(mysql_global_status_aborted_connects{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "aborted connects"
    },
    {
     "expr": "rate(mysql_global_status_connection_errors_total{monitor=\"$monitor\", instance=\"$instance\"}[$__interval]) ",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Executed commands",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_select_full_join{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "select_full_join"
    },
    {
     "expr": "rate(mysql_global_status_select_full_range_join{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "select_full_range_join"
    },
    {
     "expr": "rate(mysql_global_status_select_scan{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "select_scan"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "threads_connected"
    },
    {
     "expr": "mysql_global_variables_max_connections{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "max_connections"
    },
    {
     "expr": "mysql_global_status_threads_running{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "threads_running"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*rate(mysql_global_status_bytes_received{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "received"
    },
    {
     "expr": "8*rate(mysql_global_status_bytes_sent{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "InnoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Innodb pool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "data"
    },
    {
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "dirty"
    }
   ]
  },
  {
   "title": "Innodb IO/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_pending_fsyncs{monitor=\"$monitor\", instance=~\"$instance\"} + mysql_global_status_innodb_os_log_pending_fsyncs{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "pending_fsyncs"
    },
    {
     "expr": "mysql_global_status_innodb_data_pending_reads{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "pending_reads"
    },
    {
     "expr": "mysql_global_status_innodb_data_pending_writes{monitor=\"$monitor\", instance=~\"$instance\"} + mysql_global_status_innodb_os_log_pending_writes{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "pending_writes"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_reads{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_writes{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "writes"
    },
    {
     "expr": "rate(mysql_global_status_innodb_log_writes{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "log_writes"
    }
   ]
  },
  {
   "title": "Innodb buffer pool pages by state.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mysql_global_status_buffer_pool_pages{monitor=\"$monitor\", instance=~\"$instance\", state=~\"free|data|misc\"}) by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Tmp tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "tmp disk tables"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_files{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "tmp files"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_tables{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "tmp tables"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Time",
   "type": "graph",
   "description": "**InnoDB Row Lock Time**\n\nWhen data is locked, then that means that another ***session can NOT update that data until the lock*** is released (which unlocks the data and allows other users to update that data). Locks are usually released by either a ROLLBACK or COMMIT SQL statement.\n\nInnoDB implements standard row-level locking where there are two types of locks, [shared (S) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) and [exclusive (X) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock).\n\n* A [shared (S) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) permits the transaction that holds the lock to read a row.\n* An [exclusive (X) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock) permits the transaction that holds the lock to update or delete a row.\n\n_Average Row Lock Wait Time_ is the row lock wait time divided by the number of row locks.\\\n_Row Lock Waits_ are how many times a transaction waited on a row lock per second.\\\n_Row Lock Wait Load_ is a rolling 5 minute average of Row Lock Waits.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_lock_waits{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Row Lock Waits"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])/1000",
     "legendFormat": "Row Lock Wait Load"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])/rate(mysql_global_status_innodb_row_lock_waits{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Avg Row Lock Wait Time"
    }
   ]
  },
  {
   "title": "Engine InnoDB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_engine_innodb_queries_in_queue{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "queries_in_queue"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_engine_innodb_queries_inside_innodb{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "queries_inside_innodb"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_engine_innodb_read_views_open_inside_innodb{monitor=\"$monitor\", instance=\"$instance\"}",
     "legendFormat": "read_views_open_inside_innodb"
    }
   ]
  },
  {
   "title": "Table cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_table_open_cache{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "table_open_cache"
    },
    {
     "expr": "mysql_global_status_open_tables{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "open_tables"
    }
   ]
  },
  {
   "title": "History List",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "History List"
    }
   ]
  },
  {
   "title": "Performance Schema",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_performance_schema_sum_select_full_join{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "select_full_join"
    },
    {
     "expr": "rate(mysql_performance_schema_sum_no_index_used{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "no_index_used"
    },
    {
     "expr": "rate(mysql_performance_schema_sum_created_tmp_disk_tables{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "created_tmp_disk_tables"
    },
    {
     "expr": "mysql_slave_status_seconds_behind_master{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "slave_lag"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_trx_count{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": " transactions"
    },
    {
     "expr": "mysql_info_schema_innodb_trx_running{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": " transactions running"
    },
    {
     "expr": "mysql_info_schema_innodb_trx_running1{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": " transactions running >1s"
    },
    {
     "expr": "mysql_info_schema_innodb_trx_running10{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": " transactions running >10s"
    },
    {
     "expr": "mysql_info_schema_innodb_trx_locking1000{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "transactions locking >1000 rows"
    }
   ]
  },
  { "title": "Query Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Reads Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "avg(rate(mysql_info_schema_read_query_response_time_seconds_bucket{monitor=\"$monitor\", instance=\"$instance\"}[$__interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Writes Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "avg(rate(mysql_info_schema_write_query_response_time_seconds_bucket{monitor=\"$monitor\", instance=\"$instance\"}[5m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}