{
 "title": "RabbitMQ: overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(rabbitmq_node_up, monitor)"
   },
   {
    "name": "instance",
    "query": "label_values(rabbitmq_node_up{monitor=\"$monitor\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(process_uptime_seconds{monitor=\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nodes up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(rabbitmq_node_up{monitor=~\"$monitor\"}) by(instance)>0)"
    }
   ]
  },
  {
   "title": "Failed queues",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_state{monitor=\"$monitor\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Redeliver/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_messages_redelivered_total{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU usage, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{monitor=~\"$monitor\", container_name=~\"rabbitmq\"}[$__interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory consumption (working Set)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{monitor=~\"$monitor\", container_name=~\"rabbitmq\"}) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{monitor=~\"$monitor\", container_name=~\"rabbitmq\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{monitor=~\"$monitor\", mountpoint=\"/mnt/rabbitmq\"} / node_filesystem_size_bytes{monitor=~\"$monitor\", mountpoint=\"/mnt/rabbitmq\"})",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "FDS utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{monitor=\"$monitor\", instance=~\"$instance\"} / process_max_fds{monitor=\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages queued",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_queue_messages{monitor=~\"$monitor\", instance=~\"$instance\", queue!~\"message.*\"}) by(vhost,queue)",
     "legendFormat": "{{vhost}}/{{queue}}"
    }
   ]
  },
  {
   "title": "Exchange rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(rabbitmq_exchange_messages_published_in_total{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])) by(vhost,exchange,type)",
     "legendFormat": "{{vhost}}/{{exchange}}/{{type}} in"
    },
    {
     "expr": "max(rate(rabbitmq_exchange_messages_published_out_total{monitor=\"$monitor\", instance=~\"$instance\"}[$__interval])) by(vhost,exchange,type)",
     "legendFormat": "{{vhost}}/{{exchange}}/{{type}} out"
    }
   ]
  },
  {
   "title": "Connections and channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rabbitmq_connections{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "avg(rabbitmq_exchanges{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "exchanges"
    },
    {
     "expr": "avg(rabbitmq_channels{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "channels"
    },
    {
     "expr": "avg(rabbitmq_consumers{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "consumers"
    },
    {
     "expr": "avg(rabbitmq_queues{monitor=~\"$monitor\", instance=~\"$instance\"})",
     "legendFormat": "queues"
    }
   ]
  },
  { "title": "Stats by node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$instance queues memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_memory{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{vhost}}/{{queue}}"
    }
   ]
  },
  {
   "title": "$instance mnesia tables memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_memory_bytes{monitor=~\"$monitor\", instance=~\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}