{
 "title": "Thanos: store",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "monitor",
    "query": "label_values(thanos_store_index_cache_total_size_bytes, monitor)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(thanos_store_index_cache_total_size_bytes{monitor=~\"$monitor\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "thanos-store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query RPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{monitor=~\"$monitor\",instance=~\"$instance\"}[$__interval])) by (grpc_code, grpc_method, instance)",
       "legendFormat": "{{grpc_code}} {{grpc_method}}"
      }
     ]
    },
    {
     "title": "Response Time 99.99 Quantile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(grpc_server_handling_seconds_bucket{monitor=~\"$monitor\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Bucket IO/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(thanos_objstore_bucket_operations_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, operation)",
       "legendFormat": "bucket {{operation}}"
      },
      {
       "expr": "sum(rate(thanos_bucket_store_block_drops_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance)",
       "legendFormat": "block drops"
      },
      {
       "expr": "sum(rate(thanos_bucket_store_block_loads_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance)",
       "legendFormat": "block loads"
      }
     ]
    },
    {
     "title": "Response Size 99.99 Quantile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Operation Time Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, le, operation))",
       "legendFormat": "bucket {{operation}}"
      },
      {
       "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance,le))",
       "legendFormat": "get all"
      },
      {
       "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance,le))",
       "legendFormat": "merge"
      }
     ]
    },
    {
     "title": "Operation Failures/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (operation,instance)",
       "legendFormat": "bucket {{operation}} {{instance}}"
      },
      {
       "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance)",
       "legendFormat": "block drop {{instance}}"
      },
      {
       "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance)",
       "legendFormat": "block load {{instance}}"
      }
     ]
    },
    {
     "title": "Index cache usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "thanos_store_index_cache_total_size_bytes{monitor=~\"$monitor\",instance=~\"$instance\"}",
       "legendFormat": "index-cache {{item_type}}"
      }
     ]
    },
    {
     "title": "Cache Ops/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(thanos_store_index_cache_items_added_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, item_type)",
       "legendFormat": "added {{item_type}}"
      },
      {
       "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, item_type)",
       "legendFormat": "evicted {{item_type}}"
      },
      {
       "expr": "sum(rate(thanos_store_index_cache_requests_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, item_type)",
       "legendFormat": "requests {{item_type}}"
      },
      {
       "expr": "sum(rate(thanos_store_index_cache_hits_total{monitor=~\"$monitor\",instance=~\"$instance\"}[1m])) by (instance, item_type)",
       "legendFormat": "hits {{item_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "thanos-compact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Compactor ops/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(thanos_compact_downsample_total{monitor=\"$monitor\"}[$__interval])",
     "legendFormat": "downsample"
    },
    {
     "expr": "rate(thanos_compact_downsample_failures_total{monitor=\"$monitor\"}[$__interval])",
     "legendFormat": "fails"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{monitor=~\"$monitor\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{monitor=~\"$monitor\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{monitor=~\"$monitor\",instance=~\"$instance\", quantile=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}