apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_PATHS_PROVISIONING
            value: "/etc/grafana/prov"
          - name: GF_SERVER_ROOT_URL  # If you are behind reverse proxy
            value: "%(protocol)s://%(domain)s/admin/grafana/"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          # initialDelaySeconds: 30
          # timeoutSeconds: 1
        volumeMounts:
        - name: grafana
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/prov/datasources
        - name: grafana-prov
          mountPath: /etc/grafana/prov/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-prov
          configMap:
            name: grafana-prov
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana
          emptyDir: {}
