# http://docs.grafana.org/administration/provisioning/
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      basicAuth: false
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prov
  namespace: monitoring
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 60 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/dashboards
