apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana
